### PR TITLE
Add moving least squares functions for pointclouds and surfaces

### PR DESCRIPTION
**Pull request by jo-mueller**
This PR partially addresses #64.

It adds the functions `smooth_surface_moving_least_squares_2D`, `smooth_surface_moving_least_squares_2D_radius`, `smooth_pointcloud_moving_least_squares_2D` and `smooth_pointcloud_moving_least_squares_2D_radius`.

## Steps to verify quality:

- [x] Automated tests are passing
- [x] Tested all functions manually in the viewer
- [x] Added functions to demo notebook

### CODE REVIEW

**Comment by haesleinhuepf** [comment]
Awesome, thanks!

**Comment by haesleinhuepf** [comment]
Just a minor remark. My IDE proposes this:
image

**Comment by jo-mueller** [comment]
@haesleinhuepf 

you mean regarding the line "The radius is used to determine the number of points [...]"? I could change the points to vertices? That would be technically more correct.

**Comment by haesleinhuepf** [comment]
@jo-mueller I'm referring to the error message `Function name should be lowercase`.

**Pull request merged**
