### PR TITLE
Open3d vedo conversion

### LINKED ISSUE #14: Remove Open3D dependency
If we manage to replace all Open3D-related functions with vedo-based functions, we could make nppas a conda-package.

Related: 
* https://github.com/BiAPoL/napari-stress/issues/76
* https://github.com/conda-forge/staged-recipes/pull/19248
* https://github.com/conda-forge/staged-recipes/pull/19259

### LINKED ISSUE #22: Vedo API changes
We need to check if the API changes in recent Vedo breaks nppas:
https://github.com/marcomusy/vedo/releases/tag/v2022.4.1

### LINKED ISSUE #34: design vedo-based API carefully
I would like to rename a lot of functions before merging https://github.com/haesleinhuepf/napari-process-points-and-surfaces/pull/23

Goal: 
* functions that were there before should not be renamed or removed (backwards compatibility)
* new functions currently have the `vedo_` prefix. This is bad practice. We should rename them.

### LINKED ISSUE #38: Subsampling surfaces / simplify mesh
Hi Johannes @jo-mueller ,

I just noticed that in the upcoming open3d-free release of nppas, any mesh simplification method is missing. Do you know any good implementation to simplify surfaces/meshes? Ideally in vedo?

Thanks!

Best,
Robert

### LINKED ISSUE #39: Change error in spherefitted curvature to a warning
I'm wondering if the tools would be easier to use if we suppressed this error and replaced it with a warning. This could be done here:

https://github.com/haesleinhuepf/napari-process-points-and-surfaces/blob/a6c9113b4860917cbf6beb2b6c535e9ecced1d25/napari_process_points_and_surfaces/_quantification.py#L247-L254

By writing something like:
```
     except Exception: 
         curvature[idx] = np.nan 
         residues[idx] = np.nan
          
 if np.nan in curvature: 
     warnings.warn(f"The chosen curvature radius ({radius})" 
                       "was too small to calculate curvatures. Increase "  
                       "the radius to silence this warning.") 
```

### LINKED ISSUE #45: Measuring sphere-fitted curvature on orders of magnitude
When measuring the sphere-fitted curvature, the user needs to provide a radius. For beginners it's hard to guess a good value for this. As an attempt I added percentages of average-size as potential way for setting radii. See [example notebook](https://github.com/haesleinhuepf/napari-process-points-and-surfaces/blob/6b369295e9c6dd8ae25a7cd12a2b22a98bc87dae/docs/surface_vertex_classification.ipynb). This leads to radii that are sample dependent, which might be a bad idea, e.g. for inter-sample-comparison.

I was wondering if it makes sense to measure curvature on a order-of-magnitude basis. We could add [here](https://github.com/haesleinhuepf/napari-process-points-and-surfaces/blob/6b369295e9c6dd8ae25a7cd12a2b22a98bc87dae/napari_process_points_and_surfaces/_quantification.py#L54) a block like this:

```
SPHERE_FITTED_CURVATURE_NANO_VOXEL
SPHERE_FITTED_CURVATURE_MICRO_VOXEL
SPHERE_FITTED_CURVATURE_MILLI_VOXEL
SPHERE_FITTED_CURVATURE_DECI_VOXEL
SPHERE_FITTED_CURVATURE_VOXEL 
SPHERE_FITTED_CURVATURE_DECA_VOXEL 
SPHERE_FITTED_CURVATURE_HECTA_VOXEL 
SPHERE_FITTED_CURVATURE_KILO_VOXEL 
SPHERE_FITTED_CURVATURE_MEGA_VOXEL 
```

... but I'm not sure if this makes sense and/or if there is a better (naming) scheme.

@jo-mueller What do you think?

### LINKED ISSUE #48: Run remove_duplicate_vertices per default after marching cubes?
I'm just wondering if it wouldn't make sense to clean surfaces directly after marching cubes in general. In one of our example notebooks we demonstrate how to use this function after marching cubes. However, if marching cubes always produces duplicate vertices, shouldn't we remove them per default?

### LINKED ISSUE #49: Put number of vertices in the SurfaceTuple _repr_html_

### PR DESCRIPTION
**Pull request by haesleinhuepf**
closes #14 
closes #22 
closes #34
closes #38 
closes #39
closes #45
closes #48 
closes #49

### CODE REVIEW

**Comment by haesleinhuepf** [comment]
I'm stuck here because the mesh smoothing in vedo delivers weird results:

This is how it looks at the moment ([example notebook](https://github.com/haesleinhuepf/napari-process-points-and-surfaces/blob/62bc9b739e58fea7f3387ee13db3197667b6baa9/docs/demo.ipynb)):

image


Compared to the [open3d-version](https://github.com/haesleinhuepf/napari-process-points-and-surfaces/blob/b1eee0567e9b879e8c873d7fc3c0a01752df039c/docs/demo.ipynb):

image

**Comment by haesleinhuepf** [comment]
Tests pass locally:
```
(bio39) C:\structure\code\napari-process-points-and-surfaces>pytest
================================================= test session starts =================================================
platform win32 -- Python 3.9.15, pytest-7.2.0, pluggy-1.0.0
PyQt5 5.15.7 -- Qt runtime 5.15.6 -- Qt compiled 5.15.6
rootdir: C:\structure\code\napari-process-points-and-surfaces
plugins: anyio-3.6.2, dash-2.7.1, napari-0.4.17, napari-plugin-engine-0.2.0, npe2-0.6.1, qt-4.2.0
collected 5 items

napari_process_points_and_surfaces\_tests\test_function.py .....                                                 [100%]

================================================== warnings summary ===================================================
..\..\..\Users\haase\mambaforge\envs\bio39\lib\site-packages\vispy\app\backends\_qt.py:93
  C:\Users\haase\mambaforge\envs\bio39\lib\site-packages\vispy\app\backends\_qt.py:93: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(QT_VERSION_STR) >= '5.4.0':

..\..\..\Users\haase\AppData\Roaming\Python\Python39\site-packages\setuptools\_distutils\version.py:346
  C:\Users\haase\AppData\Roaming\Python\Python39\site-packages\setuptools\_distutils\version.py:346: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    other = LooseVersion(other)

napari_process_points_and_surfaces/_tests/test_function.py::test_something
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:341: DeprecationWarning: nppas.convex_hull() is deprecated. Use nppas.convex_hull_from_surface() instead.
    warnings.warn("nppas.convex_hull() is deprecated. Use nppas.convex_hull_from_surface() instead.", DeprecationWarning)

napari_process_points_and_surfaces/_tests/test_function.py::test_something
napari_process_points_and_surfaces/_tests/test_function.py::test_something
napari_process_points_and_surfaces/_tests/test_function.py::test_something
napari_process_points_and_surfaces/_tests/test_function.py::test_something
napari_process_points_and_surfaces/_tests/test_function.py::test_something
napari_process_points_and_surfaces/_tests/test_function.py::test_something
napari_process_points_and_surfaces/_tests/test_function.py::test_something
napari_process_points_and_surfaces/_tests/test_function.py::test_something
napari_process_points_and_surfaces/_tests/test_function.py::test_something
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:312: DeprecationWarning: nppas.to_mesh() is deprecated. Use nppas.to_vedo_mesh() instead.
    warnings.warn("nppas.to_mesh() is deprecated. Use nppas.to_vedo_mesh() instead.", DeprecationWarning)

napari_process_points_and_surfaces/_tests/test_function.py: 13 warnings
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:289: DeprecationWarning: nppas.to_vector_d() is deprecated.
    warnings.warn("nppas.to_vector_d() is deprecated.", DeprecationWarning)

napari_process_points_and_surfaces/_tests/test_function.py::test_something
napari_process_points_and_surfaces/_tests/test_function.py::test_something
napari_process_points_and_surfaces/_tests/test_function.py::test_something
napari_process_points_and_surfaces/_tests/test_function.py::test_something
napari_process_points_and_surfaces/_tests/test_function.py::test_something
napari_process_points_and_surfaces/_tests/test_function.py::test_something
napari_process_points_and_surfaces/_tests/test_function.py::test_something
napari_process_points_and_surfaces/_tests/test_function.py::test_something
napari_process_points_and_surfaces/_tests/test_function.py::test_something
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:295: DeprecationWarning: nppas.to_vector_i() is deprecated.
    warnings.warn("nppas.to_vector_i() is deprecated.", DeprecationWarning)

napari_process_points_and_surfaces/_tests/test_function.py: 10 warnings
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:329: DeprecationWarning: nppas.to_surface() is deprecated. Use nppas.to_napari_surface_data() instead.
    warnings.warn("nppas.to_surface() is deprecated. Use nppas.to_napari_surface_data() instead.", DeprecationWarning)

napari_process_points_and_surfaces/_tests/test_function.py: 23 warnings
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:307: DeprecationWarning: nppas.to_numpy() is deprecated. Use np.asarray() instead.
    warnings.warn("nppas.to_numpy() is deprecated. Use np.asarray() instead.", DeprecationWarning)

napari_process_points_and_surfaces/_tests/test_function.py::test_something
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:361: DeprecationWarning: nppas.filter_smooth_simple() is deprecated. Use nppas.smooth_surface() instead.
    warnings.warn("nppas.filter_smooth_simple() is deprecated. Use nppas.smooth_surface() instead.", DeprecationWarning)

napari_process_points_and_surfaces/_tests/test_function.py::test_something
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:402: DeprecationWarning: nppas.filter_smooth_taubin() is deprecated. Use nppas.smooth_surface() instead.
    warnings.warn("nppas.filter_smooth_taubin() is deprecated. Use nppas.smooth_surface() instead.", DeprecationWarning)

napari_process_points_and_surfaces/_tests/test_function.py::test_something
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:381: DeprecationWarning: nppas.filter_smooth_laplacian() is deprecated. Use nppas.smooth_surface() instead.
    warnings.warn("nppas.filter_smooth_laplacian() is deprecated. Use nppas.smooth_surface() instead.", DeprecationWarning)

napari_process_points_and_surfaces/_tests/test_function.py::test_something
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:446: DeprecationWarning: nppas.simplify_quadric_decimation() is deprecated. Open an issue if you are using this function and/or if you know a good replacement https://github.com/haesleinhuepf/napari-process-points-and-surfaces/issues.
    warnings.warn("nppas.simplify_quadric_decimation() is deprecated. Open an issue if you are using this function and/or if you know a good replacement https://github.com/haesleinhuepf/napari-process-points-and-surfaces/issues.", DeprecationWarning)

napari_process_points_and_surfaces/_tests/test_function.py::test_something
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:422: DeprecationWarning: nppas.simplify_vertex_clustering() is deprecated. Open an issue if you are using this function and/or if you know a good replacement https://github.com/haesleinhuepf/napari-process-points-and-surfaces/issues.
    warnings.warn("nppas.simplify_vertex_clustering() is deprecated. Open an issue if you are using this function and/or if you know a good replacement https://github.com/haesleinhuepf/napari-process-points-and-surfaces/issues.", DeprecationWarning)

napari_process_points_and_surfaces/_tests/test_function.py::test_something
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:467: DeprecationWarning: nppas.subdivide_loop() is deprecated. Use nppas.subdivide_loop_vedo() instead.
    warnings.warn("nppas.subdivide_loop() is deprecated. Use nppas.subdivide_loop_vedo() instead.", DeprecationWarning)

napari_process_points_and_surfaces/_tests/test_function.py::test_something
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:487: DeprecationWarning: nppas.sample_points_uniformly() is deprecated. Use nppas.sample_points_from_surface() instead.
    warnings.warn("nppas.sample_points_uniformly() is deprecated. Use nppas.sample_points_from_surface() instead.", DeprecationWarning)

napari_process_points_and_surfaces/_tests/test_function.py::test_something
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:510: DeprecationWarning: nppas.sample_points_poisson_disk() is deprecated. Use nppas.sample_points_from_surface() instead.
    warnings.warn("nppas.sample_points_poisson_disk() is deprecated. Use nppas.sample_points_from_surface() instead.",

napari_process_points_and_surfaces/_tests/test_function.py::test_something
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:527: DeprecationWarning: nppas.voxel_down_sample() is deprecated. Use nppas.subsample_points() instead.
    warnings.warn(

napari_process_points_and_surfaces/_tests/test_function.py::test_something
napari_process_points_and_surfaces/_tests/test_function.py::test_something
napari_process_points_and_surfaces/_tests/test_function.py::test_something
napari_process_points_and_surfaces/_tests/test_function.py::test_something
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:321: DeprecationWarning: nppas.to_point_cloud() is deprecated. Use nppas.to_napari_points_data() instead.
    warnings.warn("nppas.to_point_cloud() is deprecated. Use nppas.to_napari_points_data() instead.", DeprecationWarning)

napari_process_points_and_surfaces/_tests/test_function.py::test_something
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:550: DeprecationWarning: nppas.points_to_convex_hull_surface() is deprecated. Use nppas.create_convex_hull_from_points() instead.
    warnings.warn("nppas.points_to_convex_hull_surface() is deprecated. Use nppas.create_convex_hull_from_points() instead.", DeprecationWarning)

napari_process_points_and_surfaces/_tests/test_function.py::test_something
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:628: DeprecationWarning: nppas.fill_holes() is deprecated. Use nppas.fill_holes_in_surface() instead.
    warnings.warn(

napari_process_points_and_surfaces/_tests/test_function.py::test_something
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:597: DeprecationWarning: nppas.surface_from_point_cloud_ball_pivoting() is deprecated. Use nppas.create_convex_hull_from_points() instead.
    warnings.warn("nppas.surface_from_point_cloud_ball_pivoting() is deprecated. Use nppas.create_convex_hull_from_points() instead.", DeprecationWarning)

napari_process_points_and_surfaces/_tests/test_function.py::test_something
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:301: DeprecationWarning: nppas.to_vector_double() is deprecated.
    warnings.warn("nppas.to_vector_double() is deprecated.", DeprecationWarning)

napari_process_points_and_surfaces/_tests/test_function.py::test_something
  C:\structure\code\napari-process-points-and-surfaces\napari_process_points_and_surfaces\__init__.py:571: DeprecationWarning: nppas.surface_from_point_cloud_alpha_shape() is deprecated. Use nppas.create_convex_hull_from_points() instead.
    warnings.warn("nppas.surface_from_point_cloud_alpha_shape() is deprecated. Use nppas.create_convex_hull_from_points() instead.", DeprecationWarning)

napari_process_points_and_surfaces/_tests/test_function.py::test_curvature
  C:\Users\haase\mambaforge\envs\bio39\lib\site-packages\vedo\pointcloud.py:463: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
  To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
    C, residue, rank, _ = np.linalg.lstsq(A, f)  # solve AC=f

napari_process_points_and_surfaces/_tests/test_function.py: 64 warnings
  C:\Users\haase\mambaforge\envs\bio39\lib\site-packages\vedo\colors.py:779: PendingDeprecationWarning: The get_cmap function will be deprecated in a future version. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead.
    mp = _cm_mpl.get_cmap(name=name)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================== 5 passed, 150 warnings in 17.35s ===========================================
```

**Comment by haesleinhuepf** [comment]
Hi @jo-mueller ,

can you do me a favor and try out this branch? Especially in the context of napari-stress it might be important to check if common workflows still work. All menus with `open3d` in the name were removed and thus, I presume we need to update documentation in napari-stress if those used open3d-nppas-menus. 

Thanks!

Best,
Robert

**Comment by jo-mueller** [comment]
> can you do me a favor and try out this branch?

Can do. I'll probably do a napari-stress release next week and make sure that it's not broken by this.

**Comment by haesleinhuepf** [comment]
> I'll probably do a napari-stress release next week

Please let me know in advance @jo-mueller . I can release nppas then as well and you could link the right version here:
https://github.com/campaslab/napari-stress/blob/97f0e1c3153b5d1ec0997b69d4ec936735783512/setup.cfg#L52

**Comment by jo-mueller** [comment]
Hi @haesleinhuepf  Looks alright to me. I found a small bug in the `remove_duplicate_vertices` function (it was missing the return type annotation, PR coming). Once that is merged it should be fine on the napari-stress end.

**Comment by jo-mueller** [comment]
Awesome!

**Pull request merged**
